# Generated by Django 3.1 on 2020-08-17 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0003_auto_20200817_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='modeifed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modeifed_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
